Add directors feature
Stepashka37/java-filmorate pull request #13
Opened 2023-04-27 09:21 UTC by Zholtikov-A

2023-04-27 14:44 UTC, Antroverden requested changes
Необходимо убрать излишние запросы к базе данных.

2023-04-28 06:54 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/module/Film.java
> -    @Past(message = "Дата выхода фильма не может быть в будущем")
У нас ТЗ допускает, что дата выхода фильма может быть в будущем. А в постмане есть тест на апдейт фильма, который эту дату ему передает и наткнувшись на валидацию руинится.

2023-04-28 11:03 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
```suggestion
        List<Film> directorsFilms = jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
        return directorsFilms.isEmpty()? throw new DirectorNotFoundException("Режиссер с  id \"" + directorId + "\" не найден.") : directorsFilms;
```

2023-04-28 15:41 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        final String sqlQueryForCheck = "select COUNT(d.director_id) " +
Эту проверку можно удалить, код для проверки я написал ниже.

2023-04-28 17:07 UTC, Salaia approved these changes

2023-04-28 23:22 UTC, Antroverden approved these changes
Хорошо!

2023-04-29 10:00 UTC, Stepashka37 approved these changes

2023-04-29 10:43 UTC, VictorBobrovskiy approved these changes

2023-04-29 12:22 UTC, merged