Fix: Codestyle fixed
Stepashka37/java-filmorate pull request #18
Opened 2023-04-27 17:27 UTC by VictorBobrovskiy

2023-04-29 07:31 UTC, Salaia approved these changes

2023-04-29 07:31 UTC, Salaia commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return null;
Может, лучше вернуть пустой список? Все безопаснее, в плане NullPointerException :)

2023-04-29 09:39 UTC, Zholtikov-A requested changes

2023-04-29 09:39 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    }
Тут нет проверки наличия данных пользователей в базе.

2023-04-29 10:05 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return null;
Согласен, лучше бы пустой список

2023-04-29 11:08 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +    }
Добавил проверку в сервис

2023-04-29 11:09 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return null;
Этот класс я исправил только для того, чтобы код скомпилировался.

2023-04-29 12:51 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        return null;
исправил

2023-04-29 13:31 UTC, Stepashka37 approved these changes

2023-04-29 14:52 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/common")
Предлагаю сделать эндпоинт в соответствии тз

2023-04-29 14:52 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        usersStorage.getUser(userId);
Чекнуть 1 запросом в бд

2023-04-29 14:54 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        usersStorage.getUser(userId);
Или убрать, если это не нужно для постман тестов

2023-04-29 18:30 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/common")
/common?userId={userId}&friendId={friendId}  - если ты про это, то так не работает

2023-04-29 19:08 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        usersStorage.getUser(userId);
исправил на один запрос к бд

2023-04-29 20:27 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/common")
Ок, согласен

2023-04-29 22:26 UTC, Antroverden requested changes
Обязательно убрать такую реализацию, потому что значений в листе могут быть миллионы(в пачке есть сообщения, что ревьюер делал такое замечание по аналогичном запросу).

2023-04-29 22:26 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<User> users = usersStorage.getUsers();
А если там миллион этих юзеров? Всех будем перебирать в поисках нужных в цикле? Это точно плохая реализация.
Я имел в виду в одном запросе чекнуть есть ли эти 2 пользователя в базе, нам же не важно(как я понял) какого юзера нет. Если одного из них нет, то выбрасываем исключение, потому что у них не может быть общих фильмов(логично, потому что либо их всех нет, либо одного из них нет).
Если нам прямо очень очень важно узнать какого юзера нет(не понятно зачем), то тогда да, можно оставить прошлую версию с двумя запросами к бд.

2023-04-29 22:26 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new UserNotFoundException("Пользователь с данным id не найден " + friendId);
Да и какая нам разница какого юзера мы не нашли. Если любого нет, выбрасывает исключение и все.

2023-04-30 12:37 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<User> users = usersStorage.getUsers();
Смотри, ты в одном абзаце умудряешься предположить, что проект реальный, а не учебный и в нём будет милион юзеров. И тут же спрашиваешь, зачем нам знать, какого именно юзера нет, тк проект учебный и для тестов постмана знать нам не обязательно. Если мы делаем реальный проект, то  нам надо знать какого юзера нет, а если учебный, то юзеров в списке вернётся два, а никак не миллион. Могу вернуть два запроса

2023-04-30 12:44 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<User> users = usersStorage.getUsers();
Проект учебный, насчет миллионов это из цитаты ревьюера в основном, но и в целом выглядит этот код очень сложно.
Можно сделать 1 sql запрос который узнает есть ли в базе эти 2 пользователя или нет.
Если какого то пользователя нет, или вообще нет таких пользователей выбросить исключение, если эти пользователи есть вернуть список.

2023-04-30 14:24 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new UserNotFoundException("Пользователь с данным id не найден " + friendId);
ок

2023-04-30 14:44 UTC, Antroverden approved these changes
Ок

2023-04-30 15:13 UTC, Zholtikov-A approved these changes

2023-04-30 16:04 UTC, merged