Add reviews
Stepashka37/java-filmorate pull request #20
Opened 2023-04-27 17:58 UTC by VictorBobrovskiy

2023-04-28 13:54 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        if (review.getContent() == null || review.getContent().isBlank()) {
Уже есть проверка на null через аннотацию в поле review, проверку на blank тоже можно сделать через аннотацию.

2023-04-28 13:57 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (review.getUserId() == null || review.getFilmId() == null || review.getIsPositive() == null) {
Уже есть проверка на null через аннотацию в данных полях review

2023-04-28 15:06 UTC, Antroverden requested changes
Добавлены комментарии для улучшения кода.

2023-04-28 17:02 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (usersStorage.getUser(review.getUserId()) == null) {
Какое?

2023-04-28 17:03 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
и тут их тоже два, какое именно?

2023-04-28 17:17 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (usersStorage.getUser(review.getUserId()) == null) {
review.getFilmId()) если ничего не найдено выбросит исключение, следовательно null никогда не вернется, аналогично второе

2023-04-28 17:26 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
usersStorage.getFilm() если ничего не найдено выбросит исключение, следовательно null никогда не вернется

2023-04-28 17:46 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Ты пробовал или просто так? Если так, как ты говоришь, то метод validateReview можно просто удалить, верно же? Но если мы его удалим, то тесты не проходят. И отвергая, предлагай. Даже ревьюеры что-то предлагают, если где-то код не нравится...

2023-04-28 18:09 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Ты комментируешь старую версию кода. Валидацию ревью я убрал уже из метода

2023-04-28 18:18 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
у меня показывает, что метод filmsStorage.getFilm() все также есть.
![image](https://user-images.githubusercontent.com/115946141/235223035-63104445-61b5-43d5-a965-3a139c7b7d0e.png)

2023-04-28 18:20 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
> Но если мы его удалим, то тесты не проходят.

вот я писал.

2023-04-28 18:28 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (usersStorage.getUser(review.getUserId()) == null) {
Ты это проверял у себя или нет?

2023-04-28 18:53 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
А ты метод не удаляй, я предлагал удалить ifы. Оставь просто usersStorage.getUser(review.getUserId()), если получится, удали и второй if

2023-04-28 18:56 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Не понял. Напиши метод полностью

2023-04-28 19:00 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
```suggestion
       private void validateReview(Review review) {
       usersStorage.getUser(review.getUserId());
       filmsStorage.getFilm(review.getFilmId());
       }
```

2023-04-28 19:04 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
А смысл какой у этого метода? Как он валидирует ревью?

2023-04-28 19:11 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
> А смысл какой у этого метода? Как он валидирует ревью?

Дак этот метод же ты сделал, я только предложил упростить код и убрать ifы. Я только сократил код, от себя ничего не добавлял. Исходя из проверок, этот метод проверяет, есть ли в базе пользователь, и фильм, к которым написаны ревью. Ты говоришь без него тесты не работают, значит он важен.
Лучше тем, что удалено 4 ifа, кода стало меньше и работает он быстрее(программе не нужно выполнять условия if, а сразу исполняются команды.

2023-04-28 19:18 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Там два ифа. Они проверяют условие и выполняют команду при его выполнении. В данном случае выбрасывают исключение. Я не понимаю, что делает этот код:
      private void validateReview(Review review) {
usersStorage.getUser(review.getUserId());
filmsStorage.getFilm(review.getFilmId()); }

2023-04-28 19:31 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Эти методы, в которых мы обращаемся к базе данных сами выбросят исключение(посмотри их реализацию в DBStorage и UserStorage), если ничего не найдено.

2023-04-28 21:49 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Теперь понял. Я посмотрел на return от метода addFilm, вместо getFilm. Вот это:
 return jdbcTemplate.query("select * from film where film_id = ?", (rs, rowNum) -> makeFilm(rs), key)
                .stream().findAny().orElse(null);
По идее ты прав, но тесты не проходят...

2023-04-28 22:18 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Я тут ещё подумал, может возможно написать 1 sql запрос, который проверит, есть ли юзер и фильм в этих таблицах(таблицы заджоинить и проверить на exists). Так ещё лучше будет, всего 1 запрос.

2023-04-28 22:21 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (filmsStorage.getFilm(review.getFilmId()) == null) {
Тесты не проходили по другой причине.

2023-04-29 08:56 UTC, Zholtikov-A requested changes

2023-04-29 08:56 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    public List<Review> getFilmReviews(int filmId, int count) {
Тут нет никакой проверки наличия фильма с данным id  в базе. Вернется пустой лист независимо от того, чего нет - фильма или отзыва на него.

2023-04-29 08:56 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    }
Тут тоже нет проверки на существование данного ревью и пользователя. Вероятно, что запрос с несуществующим id вызовет ошибку БД Referential integrity constraint violation.

2023-04-29 08:56 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    }
Аналогично предыдущему замечанию.

2023-04-29 08:56 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/interfaces/ReviewStorage.java
> +    public Review getReview(int id);
public в интерфейсе не требуется.

2023-04-29 10:11 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (usersStorage.getUser(review.getUserId()) == null) {
В этом условии нет смысла, т.к. в классе Review ты уже пометил это поле аннотацией @NotNull, т.е. ревью с пустым content просто невозможно добавить, аннотация это не пропустит

2023-04-29 11:29 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    public List<Review> getFilmReviews(int filmId, int count) {
это по тз так. проверка фильма происходит в сервисе и при его отсутствии вызывается другой метод DAO getAllReviews

2023-04-29 11:36 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    }
Да. Видимо просто в тестах проверки не было.

2023-04-29 11:47 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    }
Исправляю аналогично предыдущему

2023-04-29 11:47 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/interfaces/ReviewStorage.java
> +    public Review getReview(int id);
исправлено

2023-04-29 11:53 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    }
только я в сервисе обычно валидирую

2023-04-29 14:38 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    public List<Review> getFilmReviews(int filmId, int count) {
Не понимаю в чем суть замечания, здесь передаётся айди фильма в метод, если такого фильма нет(что логично) вернётся пустой лист, айди ревью здесь не передается.

2023-04-29 14:41 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDBStorage.java
> +    public List<Review> getFilmReviews(int filmId, int count) {
Если отзывов на фильм вообще нет, то тоже вернётся пустой лист, что тоже окей, потому что их нет

2023-04-29 14:57 UTC, Antroverden requested changes

2023-04-29 14:57 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
Дублирование кода, излишнее запросы в бд, если не нужно для постман тестов, предлагаю удалить

2023-04-29 14:57 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
Дублирование кода, излишнее запросы в бд, если не нужно для постман тестов, предлагаю удалить

2023-04-29 14:57 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
Дублирование кода, излишнее запросы в бд, если не нужно для постман тестов, предлагаю удалить

2023-04-29 14:57 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
Дублирование кода, излишнее запросы в бд, если не нужно для постман тестов, предлагаю удалить

2023-04-29 19:34 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
исправил

2023-04-29 19:34 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
удалил

2023-04-29 19:34 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
исправил

2023-04-29 19:34 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        reviewStorage.getReview(id);
удалил

2023-04-29 23:04 UTC, Antroverden approved these changes

2023-04-30 07:07 UTC, Stepashka37 approved these changes

2023-04-30 15:03 UTC, Zholtikov-A approved these changes

2023-04-30 15:03 UTC, Salaia approved these changes

2023-04-30 15:51 UTC, merged