Add most populars
Stepashka37/java-filmorate pull request #21
Opened 2023-04-27 18:26 UTC by VictorBobrovskiy

2023-04-28 12:31 UTC, Antroverden requested changes
А где автоматические тесты гитхаба? Нужно, чтобы они были запущены.

2023-04-28 18:36 UTC, VictorBobrovskiy commented
> А где автоматические тесты гитхаба? Нужно, чтобы они были запущены.

Они запущены, но не пройдены из-за отсутствия режиссеров

2023-04-29 09:37 UTC, Zholtikov-A requested changes

2023-04-29 09:37 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Override
Мне кажется, в этих методах лучше будет вернуть пустой список, нежели null.

2023-04-29 09:37 UTC, Zholtikov-A commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +
Это функционал из другой ветки

2023-04-29 11:21 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +
убрал

2023-04-29 11:22 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Override
вернул

2023-04-29 15:43 UTC, Antroverden requested changes

2023-04-29 15:43 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/popular")
Предлагаю сделать эндпоинт как в тз, не сокращать его

2023-04-29 19:21 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/popular")
Мне просто интересно, а у тебя в прошлом фп как этот эндпоинт указан в коде? Параметры запроса в эндпоинт не добавляются https://www.baeldung.com/spring-request-param

2023-04-29 19:35 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/popular")
![Screenshot_20230429_223416_GitHub.jpg](https://user-images.githubusercontent.com/115946141/235321058-ff9274a4-d038-43af-8dc5-be2ba0896baf.jpg)

Здесь был указан эндпоинт в первоначальном коде, ну ок, согласен.

2023-04-29 19:37 UTC, Antroverden approved these changes
Ок

2023-04-30 07:08 UTC, Stepashka37 approved these changes

2023-04-30 15:04 UTC, Salaia approved these changes

2023-04-30 15:16 UTC, Zholtikov-A approved these changes

2023-04-30 15:51 UTC, merged