Add search
Stepashka37/java-filmorate pull request #23
Opened 2023-04-29 13:26 UTC by Stepashka37

2023-04-29 20:25 UTC, Antroverden requested changes
Добавлены комментарии по улучшению кода.

2023-04-29 20:25 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        } else if (by.size() == 1 && by.get(0).equals("title")) {
Также как и прошлый комментарий

2023-04-29 20:25 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.size() == 2 && (by.get(0).equals("director") && by.get(1).equals("title") ||
Здесь просто первое условие заменить на by.size() == 2 && contains director && contains title, тогда второе условие не нужно.
Либо так by.size() == 2 && containsAll(List.of("director", "title"))

2023-04-29 20:25 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select  F.FILM_ID, F.NAME, F.DESCRIPTION, F.RELEASE_DATE, F.DURATION, F.RATING_ID from FILM AS F " +
Вот эту строку можно вынести в константу(private static final), чтобы каждый раз не писать(такая же строка и в старых методах повторяется).

2023-04-29 20:25 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select F.FILM_ID, F.NAME, F.DESCRIPTION, F.RELEASE_DATE, F.DURATION, F.RATING_ID from FILM as F " +
Опять эта строка

2023-04-29 20:25 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            films.addAll(filmsStorage.getFilmByFilmQuery(query));
Хорошо бы это делать одним запросом sql(заджоинить таблицы, где director = ? and title = ?)
В текущей реализации мы ищем по режиссёры, а потом к тому, что получилось добавляем поиск по названию.
Как я понял в тз нужно чтобы были именно фильмы одновременно с режиссёром и названием(например, вывести все фильма режиссёра, которые начинаются на "крад", или на букву "а" и т. д.).
Здесь же мы ищем по режиссёру, потом по ко всем фильмам режиссёра добавляем все фильмы, начинающиеся на букву "а".

2023-04-29 22:20 UTC, VictorBobrovskiy commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.size() == 1 && by.get(0).equals("director")) {
а зачем?

2023-04-29 22:31 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.size() == 1 && by.get(0).equals("director")) {
Да все как обычно:
1)Меньше кода
2)Код не дублируется
3)Лучше читаемость
4)Быстрее работает

2023-04-30 07:20 UTC, Salaia approved these changes
Я не придумала, к чему придраться :)

2023-04-30 07:45 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.size() == 1 && by.get(0).equals("director")) {
Согласен, поправил

2023-04-30 07:45 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (by.size() == 2 && (by.get(0).equals("director") && by.get(1).equals("title") ||
Тоже исправил, твой вариант проще и короче)

2023-04-30 07:47 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select  F.FILM_ID, F.NAME, F.DESCRIPTION, F.RELEASE_DATE, F.DURATION, F.RATING_ID from FILM AS F " +
Я бы ее тут оставил, просто для улучшения читабельности кода и чтобы весь код sql запроса был в одном месте, поскольку проект учебный

2023-04-30 07:57 UTC, Stepashka37 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            films.addAll(filmsStorage.getFilmByFilmQuery(query));
Ты имеешь в виду, реализовать sql запрос, который будет искать фильмы у которых и в названии и в имени режиссера есть переданный query? 
Просто в постмане, тест на поиск по title и director ожидает, что ему выдаст фильм где в имени режиссера присутсвует query и фильм, у которого в имени присутствует этот же query, причем режиссер у этого фильма другой

2023-04-30 08:24 UTC, Zholtikov-A approved these changes

2023-04-30 10:07 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select  F.FILM_ID, F.NAME, F.DESCRIPTION, F.RELEASE_DATE, F.DURATION, F.RATING_ID from FILM AS F " +
Ок

2023-04-30 10:08 UTC, Antroverden commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            films.addAll(filmsStorage.getFilmByFilmQuery(query));
Ок, понял, тогда подходит

2023-04-30 10:10 UTC, Antroverden approved these changes
Ок

2023-04-30 12:17 UTC, VictorBobrovskiy approved these changes
Ок

2023-04-30 16:01 UTC, merged